version: '3'

services:
  api-typescript:
    image: api_typescript:latest
    ports:
      - 4000:4000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    
    